### PR TITLE
privilege to remove trains and replaced occurences of deprecated minetest.env:

### PR DESCRIPTION
**Pull request by gpcf**
I've added a track that stops and reverses a train. The train stops for 10 seconds and then returns towards where it came from with the same speed it had when it entered the station.

Edit: Placer texture is CC-0 (probably even public domain, for threshold of originality reasons)

Edit: I've also added a remove_trains priv that enables people to remove trains that they don't own.

### CODE REVIEW

**Review by orwell96 — COMMENTED** [review]
Hey, you revived a koala by using an undocumented modding api

**Comment by gpcf** [comment]
It should add a forceload anchor, so it also works with unloaded mapchunks. How do I add it?

**Comment by orwell96** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=10006

**Comment by gpcf** [comment]
That's not what I meant, is there a on_place method for rails?

**Comment by orwell96** [comment]
No, please not this way.
Give me some* time, it will be persistent by "living" in a table outside of the MT core.

*new year...

**Comment by gpcf** [comment]
Sounds interesting, please explain more. Would that work with 0.4.15 or just with some nightly build?

**Comment by orwell96** [comment]
This would even work with <0.4.12 I think

**Comment by gpcf** [comment]
Perfect! I asked that because I'm deploying Advtrains on my server and I don't want to update it every day, so I'm running it on stable.

**Comment by orwell96** [comment]
The first part of PR is no longer needed.

**Comment by gpcf** [comment]
Ok, removed my shitty ATC, now only contains the privilege and the replacement of obsolete functions.

**Comment by orwell96** [comment]
OK, looks good.
I assume it works.
Will come to effect when I update the zip file next time, so on next release.

**Pull request merged**
