### PR TITLE
Added a Makefile that provides small .zip files for installation

### PR DESCRIPTION
**Pull request by gpcf**
I've added a Makefile that generates the .zip file at https://en.gpcf.eu/advtrains.zip, which is about ~1.2 MB. It only contains stuff necessary to run the mod. I left the manual out, because a lot of servers don't have a graphical user interface to read it. That zip file is generated every time I push my fork of this repo.

### CODE REVIEW

**Comment by orwell96** [comment]
How does it work?

**Comment by gpcf** [comment]
It has a `post-receive` hook on my server that runs `make tarball` and loads the .zip generated by `make` onto my website. I can post the hook script later.

**Comment by orwell96** [comment]
so, i just have to merge it and your zip gnerates automatically? or what?
can't I manually trigger the process somehow (just run make?)?

**Comment by gpcf** [comment]
GitHub does not support git hooks for security reasons. You can run the process manually and make a .zip file, but you'd need to host it somewhere. My addition is just there to provide a simple way to make a .zip file to install the mod.

**Comment by orwell96** [comment]
Hosting is no problem. How do I run it?

**Comment by gpcf** [comment]
You need to add a bare repo on the server with `git init --bare advtrains.git`, then you need to add the following code into  `advtrains.git/hooks/post-receive`:

```
#!/bin/sh
export GIT_WORK_TREE=/tmp/advtrans
mkdir -p $GIT_WORK_TREE
git checkout -f
cd $GIT_WORK_TREE
make tarball
cp advtrains.* $Websitedir
```

Where `$Websitedir$` is where your website is hosted.

Then push to that repo via ssh and it should put the .zip file automatically.

**Comment by orwell96** [comment]
Ok, I think that's too overpowered. A better workflow for me:
- I have an up-to-date repo on my computer (local)
- I run something that creates a zip file.
- I upload the zip file to the server via FTP.

What command do I have to run? make tarball? OR sth. different needed?

**Comment by gpcf** [comment]
Just `make tarball`. It creates a file named `advtrains.zip`. Are you using UNIX? Then it won't be a problem.

**Comment by orwell96** [comment]
Ok, thanks. I will do that.

**Pull request merged**
