### PR TITLE
improve models and textures

### PR DESCRIPTION
**Pull request by mbruchert**
improve models and textures of steamlocomotive and wagons

(Please squash & merge)

### CODE REVIEW

**Comment by gpcf** [comment]
can you show some screenshots?

**Comment by mbruchert** [comment]
yes here:
screenshot_20170823_110407
screenshot_20170823_110458

**Comment by gpcf** [comment]
wow. The lower one is the subway?

**Comment by gpcf** [comment]
what is that blue train?

**Comment by mbruchert** [comment]
it's a train from Garmisch-Partenkirchen in germany

**Pull request merged**
