### PR TITLE
Replace deprecated methods

### PR DESCRIPTION
**Pull request by AntumDeluge**
- 'setting_get' with 'settings:get'
- 'setting_getbool' with 'settings:get_bool'

### CODE REVIEW

**Comment by orwell96** [comment]
They are deprecated not long ago, are they?
as of 0.4.15 stable, the settings object doesn't exist, does it?

**Comment by AntumDeluge** [comment]
Correct. Only development versions use the new [calls to the 'settings' object][l_settings]. So, yes, technically they are not obsolete. If you want `master` branch to be compatible with 0.4.15, then probably shouldn't merge this yet.

[l_settings]: https://github.com/minetest/minetest/blob/43d1f375d18a2fbc547a9b4f23d1354d645856ca/src/script/lua_api/l_settings.cpp#L267

**Comment by orwell96** [comment]
Ok. I will merge it some time after the 0.4.16 release

**Comment by AntumDeluge** [comment]
Sounds good.

**Pull request merged**
