### PR TITLE
Tokyo jr jamamote

### PR DESCRIPTION
**Pull request by mbruchert**
add tokyo jamamote line train

### CODE REVIEW

**Comment by mbruchert** [comment]
why do you didnt merge my PR?

**Comment by gpcf** [comment]
Wow, those are heavy textures, they come in at 150 KB. For comparison: the subway textures is just 3.5 KB. This train is probably more suited for offline playing.

**Comment by mbruchert** [comment]
here are some screenshots
screenshot_20170225_183311
screenshot_20170225_182905
screenshot_20170225_182856
screenshot_20170225_182841

**Comment by Desour** [comment]
Btw you could add this and many more trains in a separate mod in an own modpack instead of push requesting here.

**Comment by ValkyrieStella** [comment]
hey i like that!

**Comment by gpcf** [comment]
The train looks really cool, the only problem I have with it is that the textures are far too heavy. I don't know if you can lighten them, so they are under 20 KB, as I'm not experienced with textures, but that would be great if it is possible.

**Comment by ValkyrieStella** [comment]
ok i tested on single player. here's my take, the driver and passanger are way to high, the windows are like you can only see very low. maybe move the window up or the rider down. also what i got didnt look like whats on your screenshots. ?????

**Comment by gpcf** [comment]
I would replace the circular indicator and the JR logo with something more blocky, this would make the textures quite a bit lighter.

**Comment by ValkyrieStella** [comment]
actually i see i had the wrong commit. for some reason the latest was on the bottom

**Comment by ValkyrieStella** [comment]
still seems to be very high though for the rider

**Comment by orwell96** [comment]
You didn't lay down the model file in the assets directory, did you?
3 requests:
1. Please center the locomotive model inside blender (quick procedure: 1. edit mode, 2. select all, 3. Shift+S, Cursor to selected, then look how far the cursor is from the center in x/y direction (t menu, 3d cursor) and move model by that amount.
2. Couple together some random jamamote wagons and tweak the wagon_span value so that it looks good.
3. Adjust the view_offset y parameter of all seats, so people can look out of the window (it needs to be negative)

**Pull request closed without merging**
